# Data cleaning and analytics

Data cleaning is the transformation of collected data to get rid of:
- missing values
- duplicate data
- outliers

Data analytics involves:
- classification
- visualisation
- interpetation

## Types of file

### Text file (.txt)
- reading and writing line by line
- files that humans can read "by eye"
- a standard text document that contains unformatted text

### Comma separated values (.csv)
- data fields are separated (delimited) by commas
- used to store tabular data, such as a spreadsheet or database
- CSV files can be imported to and exported from programs that store data in tables, such as Microsoft Excel

## Built-in functions for file operations (Python)

### Opening a file
```python
f = open(file, mode='r', buffering=-1, encoding=None, errors=None, newline=None, closefd=True, opener=None)
```
- `file` is the only required argument, and is the relative path to the file, including the extension
- `mode` specifies how the file is opened:
  - `r`: read. Show an error if the file does not exist. This is the default mode
  - `w`: write (overwrite). Create if file does not exist
  - `a` append (at the end) write. Create if file does not exist
  - `r+` both read and write. Show an error if file does not exist
  - `w+` both read and write. Create if file does not exist

### Closing a file
Files should be closed after the necessary operations involving them have been performed, in order to free system resources, ensure data is actually written to storage and to prevent file locks.

```python
f.close()
```

### Reading from a file
There are multiple methods for reading from a file:
```python
f.read() # read all the contents of the file as one string

f.readline() # single line reading (including a newline character (\n)). Return empty string when finished reading

f.readlines() # read all the lines of a file in a list
```

### Writing to a file
There are also multiple methods to write to a file:
```python
f.write(string) # writes the contents of string to the file, returning the number of characters written.

f.writelines(sequence) # writes a sequence of strings to the file. The sequence can be any iterable object producing strings, typically a list of strings. There is no return value.
```

### `with`

A `with` block can be used to open a file more safely. The file is automatically closed when the block finishes executing, whether an error occurs or not, so there is no need to call `f.close()` manually.

```python
with open("file.txt", "r") as f:
    data = f.read()
# file automatically closed here
```

## Extracting data from ZIP files

ZIP is an archive file format that supports lossless data compression. A ZIP file may contain one or more files or directories that may have been
compressed.

To work with ZIP files, the ZipFile class needs to be imported:
```python
from zipfile import ZipFile
```

Example usage of the class, starting with files `file1.txt` and `file2.txt`, is given below:

In [1]:
# create a ZIP called example.zip containing files file1.txt and file2.txt
from zipfile import ZipFile
with ZipFile('example.zip', 'w') as myzip:
    myzip.write('file1.txt')
    myzip.write('file2.txt')
    myzip.close()

In [2]:
# open the ZIP and perform operations on the contents
with ZipFile('example.zip', 'r') as myzip:
    # list of file names in the archive
    files = myzip.namelist()
    print("Files:", files)
    # the text lines of all files to be gathered into a single list
    textlines=[]
    for file in files:
        extrdata = myzip.read(file)
        print("Contents of", file + ":", extrdata)
        # the data in the archived file is stored in the byte format, it needs to be decoded back to utf-8
        origdata = extrdata.decode('utf-8')
        origlines = origdata.splitlines()
        textlines = textlines + origlines
    print ("All lines of all files:", textlines)

Files: ['file1.txt', 'file2.txt']
Contents of file1.txt: b'line1\r\nline2\r\n'
Contents of file2.txt: b'line3\r\nline4\r\n'
All lines of all files: ['line1', 'line2', 'line3', 'line4']

## NumPy

NumPy stands for Numerical Python: 
- NumPy arrays provide an alternative way of working with data collections
- NumPy based applications generally work quicker than the same applications using ordinary Python lists and dictionaries

Pandas, which will be looked at in detail later, is based on NumPy. Pandas and NumPy share several features that seem very different from ordinary python. 

NumPy is typically imported using:

In [3]:
import numpy as np

From here on, `np` will be used in all code cells.

NumPy arrays can be created using `np.array()`. For a one-dimensional array, the indexing works the same as normal:

In [4]:
arr = np.array([1,2,3])
print(arr[1])

2

For a multi-dimensional array, the indexing is slightly different:

In [5]:
arr2d = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr2d[1,0]) # for an ordinary list, the reference would be arr2d[1][0]

6

### The axis parameter

For two dimensional arrays, the axis parameter is used to specify whether an operation should be applied to rows or columns:
- `axis = 0` applies the operation down the rows (column-wise)
- `axis = 1` applies the operation across the columns (row-wise)

The example below shows concatenation with both `axis = 0` and `axis = 1`. Note that concatenating along an axis increases the size of that axis; for example, concatenating along the row axis stacks rows and makes each column longer.

In [6]:
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])

print("Array 1:\n", arr1)
print("Array 2:\n", arr2)

(arr_conc_0) = np.concatenate((arr1,arr2), axis=0)
print(f"Concatenating vertically (along rows, axis = 0):\n {arr_conc_0}")

(arr_conc_1) = np.concatenate((arr1,arr2), axis=1)
print(f"Concatenating horizontally (along columns, axis = 1):\n {arr_conc_1}")

Array 1:
 [[1 2]
 [3 4]]
Array 2:
 [[5 6]
 [7 8]]
Concatenating vertically (along rows, axis = 0):
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Concatenating horizontally (along columns, axis = 1):
 [[1 2 5 6]
 [3 4 7 8]]

In the example above, both arrays had the same size. Concatenation can only take place along a direction if the arrays have the same size in all other directions.

In [7]:
arr3=np.array([[10,20,30],[40,50,60]])
arr4=np.array([[5,6],[7,8]])

print("Array 3:\n", arr3)
print("Array 4:\n", arr4)

# the arrays have the same row size, but different columns size
# concatenation is only possible along the column axis (axis = 1).

arr_conc_3=np.concatenate((arr3,arr4),axis=1)
print(f"Concatenating horizontally (along columns, axis = 1):\n {arr_conc_3}")

Array 3:
 [[10 20 30]
 [40 50 60]]
Array 4:
 [[5 6]
 [7 8]]
Concatenating horizontally (along columns, axis = 1):
 [[10 20 30  5  6]
 [40 50 60  7  8]]

### Filtering

NumPy arrays with Boolean values (patterns) have a special role: they can be used for filtering of other NumPy arrays.

In [8]:
arr = np.array([10,20,-5,7,-6,2]) # array to be filtered

pattern1=np.array([True,False,True,False,False,False]) # filtering mask

arr1=arr[pattern1] # apply filter

arr1

array([10, -5])

#### Creating patterns using conditions

A filtering pattern can be initialised as the output of a condition applied component-wise to the input array.

In [9]:
arr = np.array([10,20,-5,7,-6,2])
print(f"Pre-filtered Array: {arr}")

# pattern2 is the NumPy array obtained by applying the >0 component-wise to arr
# this syntax does not work for ordinary lists; arr > 0 would throw an error if arr was not a NumPy array
pattern2 = arr > 0

print(f"Filtering Mask: {pattern2}")

arr2 = arr[pattern2]

print(f"Filtered Array: {arr2}")

Pre-filtered Array: [10 20 -5  7 -6  2]
Filtering Mask: [ True  True False  True False  True]
Filtered Array: [10 20  7  2]

#### Compound filters

The `logical_and`, `logical_or`, and `logical_not` operationscan be used to create patterns for compound conditions.

In [10]:
arr = np.array([10,20,-5,7,-6,2])
print(f"Pre-filtered Array: {arr}")

pattern3 = arr > 0 # corresponds to elements greater than 0
pattern4 = arr < 20 # corresponds to elements less than 20

print(f"First pattern (>0): {pattern3}")
print(f"Second pattern (<20): {pattern4}")

pattern_and = np.logical_and(pattern3, pattern4) # corresponds to elements greater than 0 and less than 20
print(f"Logical AND of two patterns (>0 AND <20): {pattern_and}")

arr2 = arr[pattern_and]

print(f"Filtered array: {arr2}")

Pre-filtered Array: [10 20 -5  7 -6  2]
First pattern (>0): [ True  True False  True False  True]
Second pattern (<20): [ True False  True  True  True  True]
Logical AND of two patterns (>0 AND <20): [ True False False  True False  True]
Filtered array: [10  7  2]

#### Filtering using quanitfiers

Arrays can be filtered using quantifers, which leaves only the rows (or columns) where either:
- at least one value meets a specific condition (using `np.any`)
- all the values meet a specific condition (using `np.all`)

##### `np.any`

A bidimensional pattern is just a 2D NumPy array with all values being Boolean.

The `np.any` operation applied to a bidimensional pattern with `axis=1` returns a Boolean mask for the rows with `False` entries corresponding to the 'all False' rows (`True` entries indicate at least one `True` in the row).

The `np.any` operation applied to a bidimensional pattern with `axis=0` returns a Boolean mask for the columns with `False` entries corresponding to the 'all False' columns.

In [11]:
pattern = np.array([[False,True,True],[False,True,False],[False,False,False]])
print(f"Initial pattern:\n {pattern}")

row_any=np.any(pattern,axis=1)
print(f"\nnp.any row mask (axis=1):\n{row_any}")

col_any=np.any(pattern,axis=0)
print(f"\nnp.any column mask (axis=0):\n {col_any}")

Initial pattern:
 [[False  True  True]
 [False  True False]
 [False False False]]

np.any row mask (axis=1):
[ True  True False]

np.any column mask (axis=0):
 [False  True  True]

##### `np.all`

The `np.all` operation any applied to a bidimensional pattern with `axis=1` returns a Booleanmask for the rows with `True` entries corresponding to the 'all True' rows.

The `np.all` operation any applied to a bidimensional pattern with `axis=0` returns a Boolean mask for the columns with True entries corresponding to the “all True” columns.

In [12]:
pattern = np.array([[True,True,True],[False,True,False],[False,True,False]])
print(f"Initial pattern:\n {pattern}")

row_any=np.all(pattern,axis=1)
print(f"\nnp.all row mask (axis=1):\n{row_any}")

col_any=np.all(pattern,axis=0)
print(f"\nnp.all column mask (axis=0):\n {col_any}")

Initial pattern:
 [[ True  True  True]
 [False  True False]
 [False  True False]]

np.all row mask (axis=1):
[ True False False]

np.all column mask (axis=0):
 [False  True False]

The example below shows how `np.any` can be used to remove 'all negative' rows (rows containing only negative values):

In [13]:
arr=np.array([[15,-1,2],[6,-1,0],[-3,-4,-2]])
print(f"Initial array:\n {arr}")

# create a Boolean mask for non-negative entries
pattern1 = arr>=0
print(f"\nNon-negative mask:\n {pattern1}")

# remove 'all negative' rows using np.any
# keeps only rows with at least 1 True i.e., one positive value
# operate along columns (row-wise), axis = 1
arr_pos = arr[np.any(pattern1,axis=1)]
print(f"\nFiltered array:\n {arr_pos}")

Initial array:
 [[15 -1  2]
 [ 6 -1  0]
 [-3 -4 -2]]

Non-negative mask:
 [[ True False  True]
 [ True False  True]
 [False False False]]

Filtered array:
 [[15 -1  2]
 [ 6 -1  0]]

##### `np.delete`

`np.delete` is a function that can be used to remove elements, rows, or columns from an array. It doesn’t modify the original array - it returns a new array with the specified elements removed.

The function prototype is:
```python
np.delete(arr, obj, axis=None)
```
- `arr`: the input array
- `obj`: index or list of indices to remove
- `axis`: which axis to delete along (optional)
  - `axis = None`: flatten the array first, then delete elements
  - `axis=0`: delete rows
  - `axis=1`: delete columns

In [14]:
arr = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])
print(f"Initial Array:\n {arr}")
      
new_arr = np.delete(arr, 1, axis=0)  # delete row at index 1
print(f"\nArray with row at index 1 deleted:\n {new_arr}")

new_arr_2 = np.delete(arr, [0,2], axis=1)  # delete columns at index 0 and 2
print(f"\nArray with columns at indexes 0 and 2 deleted:\n {new_arr_2}")

Initial Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Array with row at index 1 deleted:
 [[1 2 3]
 [7 8 9]]

Array with columns at indexes 0 and 2 deleted:
 [[2]
 [5]
 [8]]

## Pandas

Pandas is the main Python package for data analytics. It contains a huge number of descriptive statistics operations.

The main class for storing datasets is called `DataFrame`.

Like NumPy, Pandas must be imported:

In [15]:
import pandas as pd

### `DataFrame`

The main class of Pandas is called `DataFrame`.

A `DataFrame` instance can be thought as a table with enumerated rows and named columns. 

A new `DataFrame` instance can be created from a Python dictionary:
- each dictionary key must be associated with a list and all lists must be of the same length
- the lists become the columns, the corresponding keys being the column names

In [16]:
marks={
'id': [11,41,52,8],
'algebra':[60,90,70,55],
'analysis':[40,80,80,70],
'logics':[90,80,90,80]
}

pd_marks=pd.DataFrame(marks)
pd_marks

   id  algebra  analysis  logics
0  11       60        40      90
1  41       90        80      80
2  52       70        80      90
3   8       55        70      80

#### Restriction of columns

A new `DataFrame` instance can be obtained from existing one by removal of columns.

This is important for various per row statistics:
- only the columns with values meaningful for the statistics are left

One way to restrict the columns is as follows:
- Create a list `L` with the names of columns to stay in the new `DataFrame`
- Let `df` be the `DataFrame` being restricted
- Create a `DataFrame` `df_new` by running `df_new = df[L]`

In [17]:
marks_only=['algebra','analysis','logics']
pd_marks_only=pd_marks[marks_only]
pd_marks_only

   algebra  analysis  logics
0       60        40      90
1       90        80      80
2       70        80      90
3       55        70      80

#### Descriptive statistics

There are a number of descriptive statistics that can be applied to data in a Pandas `DataFrame`. Some of these include:

| Function  | Description                      |
| --------- | -------------------------------- |
| count()   | Number of non-null observations  |
| sum()     | Sum of values                    |
| mean()    | Mean of Values                   |
| median()  | Median of Values                 |
| mode()    | Mode of values                   |
| std()     | Standard Deviation of the Values |
| min()     | Minimum Value                    |
| max()     | Maximum Value                    |
| abs()     | Absolute Value                   |
| prod()    | Product of Values                |
| cumsum()  | Cumulative Sum                   |
| cumprod() | Cumulative Product               |

We will just look at computing the mean. Most of these functions will behave similarly.

#### Mean computation

Let `df` be a `DataFrame` instance:
- `df.mean()` returns averages of each column
  - `df.mean()` is `df.mean(0)` by default, the number in the brackets specifies the axis
- `df.mean(1)` returns averages of each row
- the type of the returned object is `Series`, effectively a 1D `DataFrame`

In [18]:
mean_marks=pd_marks_only.mean(1)
mean_marks

0    63.333333
1    83.333333
2    80.000000
3    68.333333
dtype: float64

#### Adding a column

To add a new column to a `DataFrame` instance:
- use the name of the new column inside square brackets `[]` after the `DataFrame`, e.g. `df["new_col"]`
- assign a list, array, or Series of values to it

The new column will become the last one in the new data frame. 

For example, to add average marks as a new column of the `pd_marks` instance:

In [19]:
pd_marks['avg_marks']=pd_marks_only.mean(1)
pd_marks

   id  algebra  analysis  logics  avg_marks
0  11       60        40      90  63.333333
1  41       90        80      80  83.333333
2  52       70        80      90  80.000000
3   8       55        70      80  68.333333

#### Sorting by a column

To sort a `DataFrame` by a single column:
- use the `sort_value` function
- to specify the column, use parameter `by="Column Name"`
- by default, sorting is done in ascending order
  - to sort in descending order, use `ascending=False`
 
For example, to sort `pd_marks` by average marks in descending order:

In [20]:
pd_avg_sorted=pd_marks.sort_values(by='avg_marks', ascending=False)
pd_avg_sorted

   id  algebra  analysis  logics  avg_marks
1  41       90        80      80  83.333333
2  52       70        80      90  80.000000
3   8       55        70      80  68.333333
0  11       60        40      90  63.333333

#### Filtering rows

A `DataFrame` can be filtered to select only the rows that satisfy some condition.

To filter a `DataFrame`:
- create a mask by applying a condition to a single column of the `DataFrame` instance (like was done for 1D NumPy arrays)
- the mask contains `True` for rows to keep (rows that meet the condition) and `False` for rows to discard
- apply the mask to the table by using the mask inside square brackets `[]` after the `DataFrame`

For example, to filter `pd_marks` to only show rows with an `analysis` mark greater than 70:

In [24]:
analysis_min_70 = pd_marks["analysis"] > 70
print(f"Mask:\n{analysis_min_70}")

print(f"\nFiltered DataFrame:")
pd_marks[analysis_min_70]

Mask:
0    False
1     True
2     True
3    False
Name: analysis, dtype: bool

Filtered DataFrame:

   id  algebra  analysis  logics  avg_marks
1  41       90        80      80  83.333333
2  52       70        80      90  80.000000

#### Columns and index
- The names of the columns are stored in the `columns` attribute of a `DataFrame` instance.
- The numbers indexing the rows are stored in the `index` attribute of a `DataFrame` instance.
- Both attributes can be accessed directly and printed.

In [25]:
cols = pd_marks.columns
row_index = pd_marks.index

print(f"Columns:\n{cols}")
print(f"\nRows indexed with:\n{row_index}")

Columns:
Index(['id', 'algebra', 'analysis', 'logics', 'avg_marks'], dtype='object')

Rows indexed with:
RangeIndex(start=0, stop=4, step=1)

- Both the `columns` and `index` attributes are of type `Index`.
- If any of them is an interval of integers, then the type is `RangeIndex`.
- These are list like types but immutable: individual elements cannot be changed, but individual elements can be accessed and printed.

Since the `Index` and `RangeIndex` are immutable, in order to modify the columns or index of a `DataFrame`:
- Copy the attribute to a list (Pandas provides a `to_list` function).
- Change the list as desired.
- Copy the list back to the attribute.
- Note that the length of the list cannot be changed as a result of the modification, otherwise an error will be thrown.

In [27]:
col_list = pd_marks.columns.to_list()
col_list[1] = 'algorithms' # change second column from 'algebra' to 'algorithms'
pd_marks.columns = pd.Index(col_list)
ind_list = pd_marks.index.to_list()
ind_list_incr = [x+20 for x in ind_list] # increase the index of each row by 20
pd_marks.index = pd.Index(ind_list_incr)
pd_marks

    id  algorithms  analysis  logics  avg_marks
20  11          60        40      90  63.333333
21  41          90        80      80  83.333333
22  52          70        80      90  80.000000
23   8          55        70      80  68.333333

#### `Series`
- `Series` is a class of Pandas that is used for analysis of one-dimensional data sets.
- Can be created from a Python list.
- Individual elements can be accessed analogously to Python lists.
- Has the associated `index` attribute, but does not have the `columns` attribute.

In [40]:
example_series = pd.Series([4,22,81,33,-1,55]) # initialise series
example_series[1] = 6 # set value of second item to 6
example_series

0     4
1     6
2    81
3    33
4    -1
5    55
dtype: int64

#### Accessing individual values, rows, and columns

##### Accessing an individual element
- Let `df` be a `DataFrame` instance.
- Let `c` be an entry of `columns` and `i` be an entry of `index`.
- `df[c][i]` gives access to the element of `df` in row `c` with index `i`
- Note that, unlike in the ordinary Python, the column is specified first and then the row.

In [29]:
# re-initialise the table (discard changes from previous code blocks)
marks={
'id': [11,41,52,8],
'algebra':[60,90,70,55],
'analysis':[40,80,80,70],
'logics':[90,80,90,80]
}

pd_marks=pd.DataFrame(marks)
pd_marks

   id  algebra  analysis  logics
0  11       60        40      90
1  41       90        80      80
2  52       70        80      90
3   8       55        70      80

In [35]:
# the assignment will produce a FutureWarning. This can be ignored
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)

In [39]:
pd_marks["algebra"][1] = 100 # change the value in the `algebra` column, index 1, from 90 to 100
pd_marks

   id  algebra  analysis  logics
0  11       60        40      90
1  41      100        80      80
2  52       70        80      90
3   8       55        70      80

##### Accessing individual rows and columns
Individual columns and rows of a data can be accessed as `series`.

Let `df` be a `DataFrame` instance, `c` be a columns entry, `i` be an index entry.
- `df[c]` gives access to column `c`.
- `df.loc[i]` gives access to row `i`.

In [43]:
algebra_col = pd_marks["algebra"]
row_0 = pd_marks.loc[0]

print(f"Algebra Column:\n{algebra_col}")
print(f"\nRow 0:\n{row_0}")

Algebra Column:
0     60
1    100
2     70
3     55
Name: algebra, dtype: int64

Row 0:
id          11
algebra     60
analysis    40
logics      90
Name: 0, dtype: int64

Note that a `Series` instance is not the same as a `DataFrame` instance with a single column
- `pd_marks['analysis']` produces a `Series` instance.
- `L=['analysis']` and then `pd_marks[L]` produces a `DataFrame` with a single `analysis` column.
- They are not the same objects.
- In particular, the latter needs application of the `squeeze()` functions, in case it used for filtering.

### .csv files 

Data can be read from a .csv file into a `DataFrame` using the `read_csv` function:
- `df = pd.read_csv('f.csv')` copies the content of the `f.csv` file to a `DataFrame` instance `df`

Data can be written to a .csv file from a `DataFrame` using the `to_csv` function:
- `df.to_csv('f1.csv')` copies the `DataFrame` instance `df` to a file `f1.csv`

Both operations preserve the columns of the dataset.

In [44]:
pd_marks = pd.read_csv('student_marks.csv')
pd_marks

,Name,Gender,DOB,Maths,Physics,Chemistry,English,Biology,Economics,History,Civics
0,John,M,05/04/1988,55,45,56,87,21,52,89,65
1,Suresh,M,04/05/1987,75,96,78,64,90,61,58,2
2,Ramesh,M,25/05/1989,25,54,89,76,95,87,56,74
3,Jessica,F,12/08/1990,78,96,86,63,54,89,75,45
4,Jennifer,F,02/09/1989,58,96,78,46,96,77,83,53
5,Annu,F,05/04/1988,45,87,52,89,55,89,87,52
6,pooja,F,04/05/1987,55,64,61,58,75,58,64,61
7,Ritesh,M,25/05/1989,54,76,87,56,25,56,76,87
8,Farha,F,12/08/1990,55,63,89,75,78,75,63,89
9,Mukesh,M,02/09/1989,96,46,77,83,58,83,46,77

### Excel files

Excel files can be used similarly to .csv files.

Data can be read from a .csv file into a DataFrame using the read_csv function:
- `df = pd.read_excel('f.xlsx')` copies the content of the `f.xslx` file to a `DataFrame` instance `df`

Data can be written to an Excel file from a `DataFrane`, using the `to_excel` function:
- `df.to_excel('f.xlsx')` copies the `DataFrame` instance `df` to a file `f.xlsx`

In [59]:
pd_marks = pd.read_excel('student_marks.xlsx', engine="openpyxl")
pd_marks

    Name  Maths  English  History  Geography
0    Abe     70       85       90         60
1  Carol     80       80       65         80
2   John     70       70       60         95
3   Mary    100      100       50         85

### Mapping

Instead of processing cells one-by-one, the `map` function can be used to apply a function to all rows of a column.

In [60]:
def mark_to_class(mark):
    if 70<=mark: 
        return 'First' 
    elif mark in range(60,70): 
        return 'Upper second' 
    elif mark in range(50,60): 
        return 'Lower second' 
    elif mark in range(40,50): 
        return 'Third' 
    else: return 'Fail' 

pd_classes = pd_marks.copy() # make a copy of the DataFrame, to leave the original unchanged
for col in pd_classes.columns[1:]:
    pd_classes[col] = pd_classes[col].map(mark_to_class)

pd_classes

    Name  Maths English       History     Geography
0    Abe  First   First         First  Upper second
1  Carol  First   First  Upper second         First
2   John  First   First  Upper second         First
3   Mary  First   First  Lower second         First

## Missing values

Suppose that we initialize a `DataFrame` instance by reading from a .csv file where some cells are blank.   
These values will appear in the data frame as missing.   
If you print the instance, the respective values will appear as `NaN` standing for 'Not a Number’.  
Note that this is not the only possible way for occurrence missing values.

In [61]:
pd_mv = pd.read_csv('lecture5-code/missvalues.csv')
pd_mv

   col1  col2  col3
0     1   2.0     3
1     4   NaN     6

### Dealing with missing values
It is important to take care of missing values as part of data cleaning process.

Possible approaches include:
- doing nothing (ignoring the presence of missing values)
- dropping some components of a data frame that contain missing values.
- filling missing values

The choice of the approach depends on the application.

#### Ignoring missing values
It may be reasonable to simply ignore missing values:
- Consider a data frame is a 24 months salary survey for a big organization (say 1000 employees).
- The employees correspond to the rows, and the months correspond to the columns.
- For many employees (say up to 800) salary records are sporadically missing (say up to 3 months per employee).
- Suppose we need to compute average salaries of the employees.
- Then it is reasonable to compute the averages ignoring the missing entries.

In [62]:
pd_salary = pd.read_csv('lecture5-code/missingsalary.csv')
pd_salary

   id  salary June  salary July  salary August
0  23          NaN      10000.0        12000.0
1  47       8000.0          NaN         6000.0
2  96       5000.0       7000.0            NaN

In [63]:
#by default, mean() ignores missing values
means = pd_salary[pd_salary.columns[1:]].mean(1)
means

0    11000.0
1     7000.0
2     6000.0
dtype: float64

#### Dropping rows or columns
Suppose that for the same salary survey as in the previous example, one of the following happens:
- only a few employees (say 100 out of 1000 have missing entries, but the proportion of missing entries for each these employees is large (say, more than 50%).
- only a few months (say 3 out of 24) are missing, but the proportion of missing entries is large.

In this case, it is reasonable to remove the respective rows and columns with the missing values.

The `dropna` function can be used to drop rows or columns containing missing values.

In [64]:
pd_missing = pd.read_csv('lecture5-code/missvalues.csv')
pd_missing

   col1  col2  col3
0     1   2.0     3
1     4   NaN     6

In [65]:
pd_full_rows = pd_missing.dropna()
pd_full_rows

   col1  col2  col3
0     1   2.0     3

In [66]:
pd_full_columns = pd_missing.dropna(axis=1)
pd_full_columns

   col1  col3
0     1     3
1     4     6

The `dropna` function can be used to remove only the rows/columns where all values are missing, using the parameter `how='all'`.

In [70]:
pd_missing = pd.read_csv('lecture5-code/missingrow.csv')
pd_missing

   col1  col2  col3
0   1.0   2.0   3.0
1   NaN   NaN   NaN
2   4.0   NaN   6.0

In [71]:
pd_no_all_missing = pd_missing.dropna(how='all')
pd_no_all_missing

   col1  col2  col3
0   1.0   2.0   3.0
2   4.0   NaN   6.0

#### Filling missing values

##### Filling all missing values with the same value
Consider a `DataFrame` with:
- rows corresponding to students
- columns corresponding to modules

Some values are missing meaning that the corresponding student did not take the corresponding module.

If all the values need to filled (e.g. for the graduation exam board) then it is reasonable to fill the missing values with zeroes. 

This can be done with the `fillna` function.

In [73]:
pd_marks = pd.read_csv('lecture5-code/marksmissing.csv')
pd_marks

       Name Gender         DOB  Maths  Physics  Chemistry  English  Biology
0      John      M  05/04/1988     55     45.0         56     87.0       21
1    Suresh      M  04/05/1987     75     96.0         78      NaN       90
2   Jessica      F  12/08/1990     78     96.0         86     63.0       54
3  Jennifer      F  02/09/1989     58      NaN         78     46.0       96
4      Annu      F  05/04/1988     45     87.0         52     89.0       55
5    Ritesh      M  25/05/1989     54      NaN         87     56.0       25
6     Farha      F  12/08/1990     55     63.0         89     75.0       78
7    Mukesh      M  02/09/1989     96     46.0         77      NaN       58

In [74]:
pd_marks_full=pd_marks.fillna(0)
pd_marks_full

       Name Gender         DOB  Maths  Physics  Chemistry  English  Biology
0      John      M  05/04/1988     55     45.0         56     87.0       21
1    Suresh      M  04/05/1987     75     96.0         78      0.0       90
2   Jessica      F  12/08/1990     78     96.0         86     63.0       54
3  Jennifer      F  02/09/1989     58      0.0         78     46.0       96
4      Annu      F  05/04/1988     45     87.0         52     89.0       55
5    Ritesh      M  25/05/1989     54      0.0         87     56.0       25
6     Farha      F  12/08/1990     55     63.0         89     75.0       78
7    Mukesh      M  02/09/1989     96     46.0         77      0.0       58

##### Averages per row as missing values
- Let us get back to the first scenario with salaries (small proportion of entries per employee are missing).
- Assume now that we cannot ignore the missing values (e.g. due to some procedural reason).
- Then it is reasonable to fill missing entries of each employee with the average salary of that employee.

In [76]:
pd_salary = pd.read_csv('lecture5-code/missingsalary.csv')
pd_salary

   id  salary June  salary July  salary August
0  23          NaN      10000.0        12000.0
1  47       8000.0          NaN         6000.0
2  96       5000.0       7000.0            NaN

In [77]:
for i in pd_salary.index:
 pd_salary.loc[i] = pd_salary.loc[i].fillna(means[i])
pd_salary

   id  salary June  salary July  salary August
0  23      11000.0      10000.0        12000.0
1  47       8000.0       7000.0         6000.0
2  96       5000.0       7000.0         6000.0

##### Filling missing entries by 'fill forward' method
- Suppose that a data frame contains temperature observations taken once in 30 minutes at the same location.
- However, there are small missing gaps in the observation.
- It is then reasonable to fill each gap with the last temperature preceding the gap.

This can be done using `fillna` with `method='ffill'`. 

A propagation limit can be set with `limit`, which limits how many consecutive missing values can be filled with the last value before the gap.

In [79]:
pd_temp = pd.read_csv('lecture5-code/misstemp.csv')
pd_temp

    time  temperature
0  10:00          1.0
1  10:30          2.0
2  11:00          NaN
3  11:30          NaN
4  12:00          3.0
5  12:30          4.0
6  13:00          NaN
7  13:30          NaN

In [81]:
fw_temp=pd_temp.fillna(method='ffill')
fw_temp

    time  temperature
0  10:00          1.0
1  10:30          2.0
2  11:00          2.0
3  11:30          2.0
4  12:00          3.0
5  12:30          4.0
6  13:00          4.0
7  13:30          4.0

In [84]:
fw_limit=pd_temp.fillna(method='ffill',limit=1)
fw_limit

    time  temperature
0  10:00          1.0
1  10:30          2.0
2  11:00          2.0
3  11:30          NaN
4  12:00          3.0
5  12:30          4.0
6  13:00          4.0
7  13:30          NaN

### `isnull`
The `isnull()` function can be applied to a specific row or column of a `DataFrame`.

It returns a Boolean pattern, where:
- `True` entries correspond to missing values
- `False` entries correspond to existing values.
  
It provides a convenitent way to check whether a specific cell of a `DataFrame` is missing.

In [85]:
pd_mv = pd.read_csv('lecture5-code/missvalues.csv')
pd_mv

   col1  col2  col3
0     1   2.0     3
1     4   NaN     6

In [86]:
miss_column = pd_mv['col2'].isnull()
miss_column

0    False
1     True
Name: col2, dtype: bool

In [88]:
miss_row=pd_mv.loc[1].isnull()
miss_row

col1    False
col2     True
col3    False
Name: 1, dtype: bool

## Duplicates

Duplicates of a `DataFrame` are identical rows.   
Duplicates may also be restricted or subject to a subset of columns. In this case, the rows are identical in the specified set of columns but may be distinct otherwise.

The `duplicated` function produces a Boolean mask for duplicated rows, and can be restricted to a subset of columns using the `subset` parameter.

In [89]:
pd_dup_val = pd.read_csv('lecture5-code/DuplDemoRow.csv')
pd_dup_val

   col1  col2
0     1     8
1     2     3
2     1     4
3     2     7
4     1     4

In [90]:
pd_dup_val.duplicated()

0    False
1    False
2    False
3    False
4     True
dtype: bool

In [91]:
pd_dup_val.duplicated(subset=['col1'])

0    False
1    False
2     True
3     True
4     True
dtype: bool

### The need to drop values
Depending on the application, duplicates may or may not need to be removed:
- Removal is needed, for example, if the `DataFrame` provides the list of employees of some company. If some employee appears more than once, duplicate
records need to be removed.
- Removal is not needed, for example, if each row of a data frame corresponds to a shift and contains contact details of the employee who is in charge of the shift. There will be a lot of duplicate rows, and they are an important part of the information.

Assuming removal is needed, there are a number of possible ways to implement it.

### Removal of full duplicates
The `drop_duplicates` function can be used to remove fully duplicate rows.

In [92]:
dropped=pd_dup_val.drop_duplicates()
dropped

   col1  col2
0     1     8
1     2     3
2     1     4
3     2     7

### Removal of duplicates subject to a subset of columns
When removing duplicates subject to a subset of columns, the rows may contain distinct values for the other columns not included in the subset. After removal of the duplicate rows, only one value will remain for these other rows.  

`drop_duplicates` has the parameter `keep` which can be used to set which values to keep for the columns in subset:
- `keep='first'` keeps that first occurring value. It is the default option
- `keep='last'` keeps the last occurring value

In [96]:
pd_dup_val = pd.read_csv('lecture5-code/DuplDemoRow.csv')
pd_dup_val

   col1  col2
0     1     8
1     2     3
2     1     4
3     2     7
4     1     4

In [98]:
dropped1 = pd_dup_val.drop_duplicates(subset=['col1']) # keep first occuring (default)
dropped1

   col1  col2
0     1     8
1     2     3

In [99]:
dropped2=pd_dup_val.drop_duplicates(subset=['col1'], keep='last') # keep last occuring
dropped2

   col1  col2
3     2     7
4     1     4

## Outliers
Let `df` be a `DataFrame` instance and `col` be a column of `df`.   
A value occurring in `col` is an outlier if it occurs rarely in `col`. 

The task of removal of outliers involves removing the rows of `df` whose values at `col` are outliers.

### Rare occurence
In order to design an algorithm for identification of outliers, there needs to be a precise specification of a rare occurrence.

We will consider the following three interpretations:
- Threshold limit: We set some threshold limit, say 3, and all the values that occur less than 3 times are considered outliers.
- Threshold limit for clusters: We classify all the values into several classes and again set a limit, say 3. A value is considered an outlier if its class occurs less than 3 times.
- Quartiles based: We apply a standard statistical methodology involving quartiles and interquartile range

### `value_counts`
The `value_counts()` function can be applied to a `Series`.   
It maps each value of the `Series` to its frequency, and orders the values in decreasing order.

In [101]:
test_dict={
 'key1': ['a','b','a','a','a','b','a','b'],
 'key2': ['c','c','c','c','d','d','d','d'],
 'num1':[1,1,3,3,3,6,7,8],
 'num2':[40,35,30,25,20,15,10,5]
}
freq_test=pd.DataFrame(test_dict)
val_counts=freq_test['num1'].value_counts() # count the frequency of teach value in column `num1`
val_counts

num1
3    3
1    2
6    1
7    1
8    1
Name: count, dtype: int64