# Data cleaning and analytics

Data cleaning is the transformation of collected data to get rid of:
- missing values
- duplicate data
- outliers

Data analytics involves:
- classification
- visualisation
- interpetation

## Types of file

### Text file (.txt)
- reading and writing line by line
- files that humans can read "by eye"
- a standard text document that contains unformatted text

### Comma separated values (.csv)
- data fields are separated (delimited) by commas
- used to store tabular data, such as a spreadsheet or database
- CSV files can be imported to and exported from programs that store data in tables, such as Microsoft Excel

## Built-in functions for file operations (Python)

### Opening a file
```python
f = open(file, mode='r', buffering=-1, encoding=None, errors=None, newline=None, closefd=True, opener=None)
```
- `file` is the only required argument, and is the relative path to the file, including the extension
- `mode` specifies how the file is opened:
  - `r`: read. Show an error if the file does not exist. This is the default mode
  - `w`: write (overwrite). Create if file does not exist
  - `a` append (at the end) write. Create if file does not exist
  - `r+` both read and write. Show an error if file does not exist
  - `w+` both read and write. Create if file does not exist

### Closing a file
Files should be closed after the necessary operations involving them have been performed, in order to free system resources, ensure data is actually written to storage and to prevent file locks.

```python
f.close()
```

### Reading from a file
There are multiple methods for reading from a file:
```python
f.read() # read all the contents of the file as one string

f.readline() # single line reading (including a newline character (\n)). Return empty string when finished reading

f.readlines() # read all the lines of a file in a list
```

### Writing to a file
There are also multiple methods to write to a file:
```python
f.write(string) # writes the contents of string to the file, returning the number of characters written.

f.writelines(sequence) # writes a sequence of strings to the file. The sequence can be any iterable object producing strings, typically a list of strings. There is no return value.
```

## `with`

A `with` block can be used to open a file more safely. The file is automatically closed when the block finishes executing, whether an error occurs or not, so there is no need to call `f.close()` manually.

```python
with open("file.txt", "r") as f:
    data = f.read()
# file automatically closed here
```

## Extracting data from ZIP files

ZIP is an archive file format that supports lossless data compression. A ZIP file may contain one or more files or directories that may have been
compressed.

To work with ZIP files, the ZipFile class needs to be imported:
```python
from zipfile import ZipFile
```

Example usage of the class, starting with files `file1.txt` and `file2.txt`, is given below:

In [1]:
# create a ZIP called example.zip containing files file1.txt and file2.txt
from zipfile import ZipFile
with ZipFile('example.zip', 'w') as myzip:
    myzip.write('file1.txt')
    myzip.write('file2.txt')
    myzip.close()

In [2]:
# open the ZIP and perform operations on the contents
with ZipFile('example.zip', 'r') as myzip:
    # list of file names in the archive
    files = myzip.namelist()
    print("Files:", files)
    # the text lines of all files to be gathered into a single list
    textlines=[]
    for file in files:
        extrdata = myzip.read(file)
        print("Contents of", file + ":", extrdata)
        # the data in the archived file is stored in the byte format, it needs to be decoded back to utf-8
        origdata = extrdata.decode('utf-8')
        origlines = origdata.splitlines()
        textlines = textlines + origlines
    print ("All lines of all files:", textlines)

Files: ['file1.txt', 'file2.txt']
Contents of file1.txt: b'line1\r\nline2\r\n'
Contents of file2.txt: b'line3\r\nline4\r\n'
All lines of all files: ['line1', 'line2', 'line3', 'line4']

## NumPy

NumPy stands for Numerical Python: 
- NumPy arrays provide an alternative way of working with data collections
- NumPy based applications generally work quicker than the same applications using ordinary Python lists and dictionaries

Pandas, which will be looked at in detail later, is based on NumPy. Pandas and NumPy share several features that seem very different from ordinary python. 

NumPy is typically imported using:

In [3]:
import numpy as np

From here on, `np` will be used in all code cells.

NumPy arrays can be created using `np.array()`. For a one-dimensional array, the indexing works the same as normal:

In [4]:
arr = np.array([1,2,3])
print(arr[1])

2

For a multi-dimensional array, the indexing is slightly different:

In [5]:
arr2d = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr2d[1,0]) # for an ordinary list, the reference would be arr2d[1][0]

6

### The axis parameter

For two dimensional arrays, the axis parameter is used to specify whether an operation should be applied to rows or columns:
- `axis = 0` applies the operation down the rows (column-wise)
- `axis = 1` applies the operation across the columns (row-wise)

The example below shows concatenation with both `axis = 0` and `axis = 1`. Note that concatenating along an axis increases the size of that axis; for example, concatenating along the row axis stacks rows and makes each column longer.

In [6]:
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])

print("Array 1:\n", arr1)
print("Array 2:\n", arr2)

(arr_conc_0) = np.concatenate((arr1,arr2), axis=0)
print(f"Concatenating vertically (along rows, axis = 0):\n {arr_conc_0}")

(arr_conc_1) = np.concatenate((arr1,arr2), axis=1)
print(f"Concatenating horizontally (along columns, axis = 1):\n {arr_conc_1}")

Array 1:
 [[1 2]
 [3 4]]
Array 2:
 [[5 6]
 [7 8]]
Concatenating vertically (along rows, axis = 0):
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Concatenating horizontally (along columns, axis = 1):
 [[1 2 5 6]
 [3 4 7 8]]

In the example above, both arrays had the same size. Concatenation can only take place along a direction if the arrays have the same size in all other directions.

In [7]:
arr3=np.array([[10,20,30],[40,50,60]])
arr4=np.array([[5,6],[7,8]])

print("Array 3:\n", arr3)
print("Array 4:\n", arr4)

# the arrays have the same row size, but different columns size
# concatenation is only possible along the column axis (axis = 1).

arr_conc_3=np.concatenate((arr3,arr4),axis=1)
print(f"Concatenating horizontally (along columns, axis = 1):\n {arr_conc_3}")

Array 3:
 [[10 20 30]
 [40 50 60]]
Array 4:
 [[5 6]
 [7 8]]
Concatenating horizontally (along columns, axis = 1):
 [[10 20 30  5  6]
 [40 50 60  7  8]]

### Filtering

NumPy arrays with Boolean values (patterns) have a special role: they can be used for filtering of other NumPy arrays.

In [8]:
arr = np.array([10,20,-5,7,-6,2]) # array to be filtered

pattern1=np.array([True,False,True,False,False,False]) # filtering mask

arr1=arr[pattern1] # apply filter

arr1

array([10, -5])

#### Creating patterns using conditions

A filtering pattern can be initialised as the output of a condition applied component-wise to the input array.

In [9]:
arr = np.array([10,20,-5,7,-6,2])
print(f"Pre-filtered Array: {arr}")

# pattern2 is the NumPy array obtained by applying the >0 component-wise to arr
# this syntax does not work for ordinary lists; arr > 0 would throw an error if arr was not a NumPy array
pattern2 = arr > 0

print(f"Filtering Mask: {pattern2}")

arr2 = arr[pattern2]

print(f"Filtered Array: {arr2}")

Pre-filtered Array: [10 20 -5  7 -6  2]
Filtering Mask: [ True  True False  True False  True]
Filtered Array: [10 20  7  2]

#### Compound filters

The `logical_and`, `logical_or`, and `logical_not` operationscan be used to create patterns for compound conditions.

In [10]:
arr = np.array([10,20,-5,7,-6,2])
print(f"Pre-filtered Array: {arr}")

pattern3 = arr > 0 # corresponds to elements greater than 0
pattern4 = arr < 20 # corresponds to elements less than 20

print(f"First pattern (>0): {pattern3}")
print(f"Second pattern (<20): {pattern4}")

pattern_and = np.logical_and(pattern3, pattern4) # corresponds to elements greater than 0 and less than 20
print(f"Logical AND of two patterns (>0 AND <20): {pattern_and}")

arr2 = arr[pattern_and]

print(f"Filtered array: {arr2}")

Pre-filtered Array: [10 20 -5  7 -6  2]
First pattern (>0): [ True  True False  True False  True]
Second pattern (<20): [ True False  True  True  True  True]
Logical AND of two patterns (>0 AND <20): [ True False False  True False  True]
Filtered array: [10  7  2]

#### Filtering using quanitfiers

Arrays can be filtered using quantifers, which leaves only the rows (or columns) where either:
- at least one value meets a specific condition (using `np.any`)
- all the values meet a specific condition (using `np.all`)

##### `np.any`

A bidimensional pattern is just a 2D NumPy array with all values being Boolean.

The `np.any` operation applied to a bidimensional pattern with `axis=1` returns a Boolean mask for the rows with `False` entries corresponding to the 'all False' rows (`True` entries indicate at least one `True` in the row).

The `np.any` operation applied to a bidimensional pattern with `axis=0` returns a Boolean mask for the columns with `False` entries corresponding to the 'all False' columns.

In [11]:
pattern = np.array([[False,True,True],[False,True,False],[False,False,False]])
print(f"Initial pattern:\n {pattern}")

row_any=np.any(pattern,axis=1)
print(f"\nnp.any row mask (axis=1):\n{row_any}")

col_any=np.any(pattern,axis=0)
print(f"\nnp.any column mask (axis=0):\n {col_any}")

Initial pattern:
 [[False  True  True]
 [False  True False]
 [False False False]]

np.any row mask (axis=1):
[ True  True False]

np.any column mask (axis=0):
 [False  True  True]

##### `np.all`

The `np.all` operation any applied to a bidimensional pattern with `axis=1` returns a Booleanmask for the rows with `True` entries corresponding to the 'all True' rows.

The `np.all` operation any applied to a bidimensional pattern with `axis=0` returns a Boolean mask for the columns with True entries corresponding to the “all True” columns.

In [12]:
pattern = np.array([[True,True,True],[False,True,False],[False,True,False]])
print(f"Initial pattern:\n {pattern}")

row_any=np.all(pattern,axis=1)
print(f"\nnp.all row mask (axis=1):\n{row_any}")

col_any=np.all(pattern,axis=0)
print(f"\nnp.all column mask (axis=0):\n {col_any}")

Initial pattern:
 [[ True  True  True]
 [False  True False]
 [False  True False]]

np.all row mask (axis=1):
[ True False False]

np.all column mask (axis=0):
 [False  True False]

The example below shows how `np.any` can be used to remove 'all negative' rows (rows containing only negative values):

In [13]:
arr=np.array([[15,-1,2],[6,-1,0],[-3,-4,-2]])
print(f"Initial array:\n {arr}")

# create a Boolean mask for non-negative entries
pattern1 = arr>=0
print(f"\nNon-negative mask:\n {pattern1}")

# remove 'all negative' rows using np.any
# keeps only rows with at least 1 True i.e., one positive value
# operate along columns (row-wise), axis = 1
arr_pos = arr[np.any(pattern1,axis=1)]
print(f"\nFiltered array:\n {arr_pos}")

Initial array:
 [[15 -1  2]
 [ 6 -1  0]
 [-3 -4 -2]]

Non-negative mask:
 [[ True False  True]
 [ True False  True]
 [False False False]]

Filtered array:
 [[15 -1  2]
 [ 6 -1  0]]

##### `np.delete`

`np.delete` is a function that can be used to remove elements, rows, or columns from an array. It doesn’t modify the original array - it returns a new array with the specified elements removed.

The function prototype is:
```python
np.delete(arr, obj, axis=None)
```
- `arr`: the input array
- `obj`: index or list of indices to remove
- `axis`: which axis to delete along (optional)
  - `axis = None`: flatten the array first, then delete elements
  - `axis=0`: delete rows
  - `axis=1`: delete columns

In [14]:
arr = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])
print(f"Initial Array:\n {arr}")
      
new_arr = np.delete(arr, 1, axis=0)  # delete row at index 1
print(f"\nArray with row at index 1 deleted:\n {new_arr}")

new_arr_2 = np.delete(arr, [0,2], axis=1)  # delete columns at index 0 and 2
print(f"\nArray with columns at indexes 0 and 2 deleted:\n {new_arr_2}")

Initial Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Array with row at index 1 deleted:
 [[1 2 3]
 [7 8 9]]

Array with columns at indexes 0 and 2 deleted:
 [[2]
 [5]
 [8]]

## Pandas

Pandas is the main Python package for data analytics. It contains a huge number of descriptive statistics operations.

The main class for storing datasets is called `DataFrame`.

Like NumPy, Pandas must be imported:

In [15]:
import pandas as pd

### `DataFrame`

The main class of Pandas is called `DataFrame`.

A `DataFrame` instance can be thought as a table with enumerated rows and named columns. 

A new `DataFrame` instance can be created from a Python dictionary:
- each dictionary key must be associated with a list and all lists must be of the same length
- the lists become the columns, the corresponding keys being the column names

In [16]:
marks={
'id': [11,41,52,8],
'algebra':[60,90,70,55],
'analysis':[40,80,80,70],
'logics':[90,80,90,80]
}

pd_marks=pd.DataFrame(marks)
pd_marks

   id  algebra  analysis  logics
0  11       60        40      90
1  41       90        80      80
2  52       70        80      90
3   8       55        70      80

#### Restriction of columns

A new `DataFrame` instance can be obtained from existing one by removal of columns.

This is important for various per row statistics:
- only the columns with values meaningful for the statistics are left

One way to restrict the columns is as follows:
- Create a list `L` with the names of columns to stay in the new `DataFrame`
- Let `df` be the `DataFrame` being restricted
- Create a `DataFrame` `df_new` by running `df_new = df[L]`

In [17]:
marks_only=['algebra','analysis','logics']
pd_marks_only=pd_marks[marks_only]
pd_marks_only

   algebra  analysis  logics
0       60        40      90
1       90        80      80
2       70        80      90
3       55        70      80

#### Descriptive statistics

There are a number of descriptive statistics that can be applied to data in a Pandas `DataFrame`. Some of these include:

| Function  | Description                      |
| --------- | -------------------------------- |
| count()   | Number of non-null observations  |
| sum()     | Sum of values                    |
| mean()    | Mean of Values                   |
| median()  | Median of Values                 |
| mode()    | Mode of values                   |
| std()     | Standard Deviation of the Values |
| min()     | Minimum Value                    |
| max()     | Maximum Value                    |
| abs()     | Absolute Value                   |
| prod()    | Product of Values                |
| cumsum()  | Cumulative Sum                   |
| cumprod() | Cumulative Product               |

We will just look at computing the mean. Most of these functions will behave similarly.

#### Mean computation

Let `df` be a `DataFrame` instance:
- `df.mean()` returns averages of each column
  - `df.mean()` is `df.mean(0)` by default, the number in the brackets specifies the axis
- `df.mean(1)` returns averages of each row
- the type of the returned object is `Series`, effectively a 1D `DataFrame`

In [18]:
mean_marks=pd_marks_only.mean(1)
mean_marks

0    63.333333
1    83.333333
2    80.000000
3    68.333333
dtype: float64

#### Adding a column

To add a new column to a `DataFrame` instance:
- use the name of the new column inside square brackets `[]` after the `DataFrame`, e.g. `df["new_col"]`
- assign a list, array, or Series of values to it

The new column will become the last one in the new data frame. 

For example, to add average marks as a new column of the `pd_marks` instance:

In [19]:
pd_marks['avg_marks']=pd_marks_only.mean(1)
pd_marks

   id  algebra  analysis  logics  avg_marks
0  11       60        40      90  63.333333
1  41       90        80      80  83.333333
2  52       70        80      90  80.000000
3   8       55        70      80  68.333333

#### Sorting by a column

To sort a `DataFrame` by a single column:
- use the `sort_value` function
- to specify the column, use parameter `by="Column Name"`
- by default, sorting is done in ascending order
  - to sort in descending order, use `ascending=False`
 
For example, to sort `pd_marks` by average marks in descending order:

In [20]:
pd_avg_sorted=pd_marks.sort_values(by='avg_marks', ascending=False)
pd_avg_sorted

   id  algebra  analysis  logics  avg_marks
1  41       90        80      80  83.333333
2  52       70        80      90  80.000000
3   8       55        70      80  68.333333
0  11       60        40      90  63.333333